
DROP TABLE IF EXIST game;

create table game(
    game_id INT generated by default as identity primary key,
    game_title VARCHAR(255),
    quantity INT,
    price DECIMAL(5, 2) 
);
\copy game from './data.game.csv' with csv header;


DROP TABLE IF EXIST action_figure(
    
)